apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Allow EKS worker nodes to connect
    - rolearn: arn:aws:iam::779846799257:role/eksctl-react-app-cluster-nodegroup-NodeInstanceRole-clYqAMHqgpFy
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    # Allow CodeBuild to deploy to EKS
    - rolearn: arn:aws:iam::779846799257:role/codebuild-react-app-build-service-role
      username: codebuild
      groups:
        - system:masters
