version: 0.2

env:
  variables:
    CLUSTER_NAME: react-app-test
    REGION: us-east-1
    REPOSITORY_URI: 779846799257.dkr.ecr.us-east-1.amazonaws.com/react-app-repo
    DEPLOYMENT_NAME: react-app-deployment
    CONTAINER_NAME: react-app-container

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.33.0/2024-07-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Configuring access to EKS..."
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Updating deployment image..."
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG --record
      - echo "Applying other manifests..."
      - kubectl apply -f k8s/

  post_build:
    commands:
      - echo "Waiting for deployment rollout..."
      - kubectl rollout status deployment/$DEPLOYMENT_NAME
      - echo "Deployment completed successfully ✅"
