pipeline:
  name: Build hello_reactapp_aws_sdlc_demo
  identifier: Build_hello_reactapp_aws_sdlc_demo_1761590496345
  projectIdentifier: reactapp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: AWS_Connector
                    region: us-east-1
                    account: "779846799257"
                    imageName: react-app
                    tags:
                      - latest
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: hello_reactapp_aws_sdlc_demo
        build: <+input>
