- name: Deploy React App Container
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Login to AWS ECR
      shell: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 779846799257.dkr.ecr.us-east-1.amazonaws.com
      args:
        executable: /bin/bash

    - name: Pull latest Docker image
      shell: docker pull 779846799257.dkr.ecr.us-east-1.amazonaws.com/react-app-repo:latest

    - name: Stop old container
      shell: docker rm -f react-app || true

    - name: Run new container
      shell: docker run -d --name react-app -p 80:80 779846799257.dkr.ecr.us-east-1.amazonaws.com/react-app-repo:latest
