name: Build and Push to ECR

on:
  push:
    branches: [ hello_aws_sdlc_demo ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v3

      - name: Build, Tag, and Push Image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Step 1: Build local Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

          # Step 2: Tag image for ECR (example below)
          # Example: docker tag react-frontend:a1b2c3d4 123456789012.dkr.ecr.us-east-1.amazonaws.com/react-frontend:a1b2c3d4
          docker tag react-app-repo:$IMAGE_TAG 779846799257.dkr.ecr.us-east-1.amazonaws.com/react-app-repo:$IMAGE_TAG

          # Step 3: Push image to ECR
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Output Image URI
        run: 'echo "✅ Image pushed to: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}"'
